version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - TZ=America/Toronto
    volumes:
      - /root/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
