version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always

    volumes:
      - /home/yangjeep/data/uptimekuma:/app/data

    ports:
      - "3001:3001"

    networks:
      internal_net:
        ipv4_address: "172.31.0.10"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-uptimekuma
    restart: always

    command: tunnel run

    environment:
      - TUNNEL_TOKEN=${CFD_TOKEN}

    networks:
      internal_net:
      dmz_vlan:
        ipv4_address: "10.25.254.130"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.31.0.0/24"
          gateway: "172.31.0.1"

  dmz_vlan:
    external: true
    name: dmz_vlan
